<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RecipeSeeder extends Seeder
{
    public function run(): void
    {
        $now = now();

        // Build lookup maps for ingredients, equipment, and dietary restrictions
        $ingredients = DB::table('ingredients')->pluck('id', 'name')->toArray();
        $equipment = DB::table('equipment')->pluck('id', 'name')->toArray();
        $dietaryRestrictions = DB::table('dietary_restrictions')->pluck('id', 'name')->toArray();

        $recipes = [
            // ===== ALMUSAL (Breakfast) =====
            [
                'name' => 'Sinangag na Kanin at Itlog',
                'description' => 'Classic Filipino garlic fried rice paired with a fried egg. A staple breakfast that is quick, affordable, and filling.',
                'meal_type' => 'almusal',
                'difficulty' => 'madali',
                'cook_time_minutes' => 10,
                'servings' => 2,
                'calories' => 350.00,
                'protein' => 12.00,
                'iron' => 1.80,
                'vitamin_c' => 0.00,
                'instructions' => json_encode([
                    'Magpainit ng mantika sa kawali.',
                    'Igisa ang bawang hanggang gumintong kulay.',
                    'Ilagay ang kanin at haluin ng mabuti.',
                    'Lagyan ng asin at paminta ayon sa panlasa.',
                    'Sa hiwalay na kawali, magprito ng itlog.',
                    'Ihain ang sinangag kasama ang pritong itlog.',
                ]),
                'ingredients' => [
                    ['name' => 'Rice (bigas)', 'quantity' => 2, 'unit' => 'cups', 'estimated_cost' => 17.00],
                    ['name' => 'Garlic (bawang)', 'quantity' => 6, 'unit' => 'cloves', 'estimated_cost' => 3.00],
                    ['name' => 'Eggs', 'quantity' => 2, 'unit' => 'piece', 'estimated_cost' => 16.00],
                    ['name' => 'Cooking oil', 'quantity' => 2, 'unit' => 'tbsp', 'estimated_cost' => 2.00],
                    ['name' => 'Salt (asin)', 'quantity' => 1, 'unit' => 'pinch', 'estimated_cost' => 0.50],
                ],
                'equipment' => ['Kalan', 'Kawali'],
                'dietary_flags' => ['Eggs', 'Vegan', 'Vegetarian'],
            ],
            [
                'name' => 'Champorado',
                'description' => 'Sweet chocolate rice porridge, a beloved Filipino comfort food for rainy mornings. Often paired with tuyo.',
                'meal_type' => 'almusal',
                'difficulty' => 'madali',
                'cook_time_minutes' => 20,
                'servings' => 4,
                'calories' => 280.00,
                'protein' => 5.00,
                'iron' => 2.50,
                'vitamin_c' => 0.00,
                'instructions' => json_encode([
                    'Pakuluan ang bigas sa tubig hanggang lumambot.',
                    'Ilagay ang cocoa powder o tablea at haluin.',
                    'Lagyan ng asukal ayon sa panlasa.',
                    'Lutuin sa mahinang apoy ng 10 minuto habang hinahalo.',
                    'Ihain na mainit. Pwedeng lagyan ng gatas.',
                ]),
                'ingredients' => [
                    ['name' => 'Rice (bigas)', 'quantity' => 1, 'unit' => 'cup', 'estimated_cost' => 8.00],
                    ['name' => 'Sugar', 'quantity' => 4, 'unit' => 'tbsp', 'estimated_cost' => 3.00],
                ],
                'equipment' => ['Kalan', 'Palayok'],
                'dietary_flags' => ['Vegan'],
            ],
            [
                'name' => 'Pandesal at Peanut Butter',
                'description' => 'Warm pandesal rolls spread with creamy peanut butter. The simplest and most budget-friendly Filipino breakfast.',
                'meal_type' => 'almusal',
                'difficulty' => 'madali',
                'cook_time_minutes' => 5,
                'servings' => 2,
                'calories' => 250.00,
                'protein' => 8.00,
                'iron' => 1.20,
                'vitamin_c' => 0.00,
                'instructions' => json_encode([
                    'Initin ang pandesal sa oven o kalan.',
                    'Hiwain ang pandesal sa gitna.',
                    'Lagyan ng peanut butter.',
                    'Ihain kasama ng mainit na kape o tsokolate.',
                ]),
                'ingredients' => [
                    ['name' => 'Bread (pandesal)', 'quantity' => 6, 'unit' => 'piece', 'estimated_cost' => 12.00],
                    ['name' => 'Peanut butter', 'quantity' => 3, 'unit' => 'tbsp', 'estimated_cost' => 6.00],
                ],
                'equipment' => ['Kalan'],
                'dietary_flags' => ['Nuts', 'Gluten'],
            ],
            [
                'name' => 'Lugaw',
                'description' => 'Comforting Filipino rice porridge seasoned with ginger and garlic. Perfect for cold mornings or when feeling under the weather.',
                'meal_type' => 'almusal',
                'difficulty' => 'madali',
                'cook_time_minutes' => 25,
                'servings' => 4,
                'calories' => 180.00,
                'protein' => 4.00,
                'iron' => 1.00,
                'vitamin_c' => 1.00,
                'instructions' => json_encode([
                    'Igisa ang bawang, sibuyas, at luya sa mantika.',
                    'Ilagay ang bigas at haluin ng 2 minuto.',
                    'Buhusan ng tubig at pakuluan.',
                    'Lutuin sa mahinang apoy ng 20 minuto habang hinahalo paminsan-minsan.',
                    'Lagyan ng patis at paminta.',
                    'Ihain na mainit na may tokwa, itlog, o kalamansi.',
                ]),
                'ingredients' => [
                    ['name' => 'Rice (bigas)', 'quantity' => 1, 'unit' => 'cup', 'estimated_cost' => 8.00],
                    ['name' => 'Ginger (luya)', 'quantity' => 1, 'unit' => 'thumb', 'estimated_cost' => 1.50],
                    ['name' => 'Garlic (bawang)', 'quantity' => 4, 'unit' => 'cloves', 'estimated_cost' => 2.00],
                    ['name' => 'Onion (sibuyas)', 'quantity' => 1, 'unit' => 'piece', 'estimated_cost' => 6.00],
                    ['name' => 'Fish sauce (patis)', 'quantity' => 2, 'unit' => 'tbsp', 'estimated_cost' => 1.50],
                    ['name' => 'Cooking oil', 'quantity' => 1, 'unit' => 'tbsp', 'estimated_cost' => 1.00],
                ],
                'equipment' => ['Kalan', 'Palayok'],
                'dietary_flags' => [],
            ],
            [
                'name' => 'Tortang Talong',
                'description' => 'Grilled eggplant flattened and dipped in egg batter then fried. A simple yet satisfying Filipino breakfast dish.',
                'meal_type' => 'almusal',
                'difficulty' => 'madali',
                'cook_time_minutes' => 15,
                'servings' => 2,
                'calories' => 220.00,
                'protein' => 10.00,
                'iron' => 1.50,
                'vitamin_c' => 3.00,
                'instructions' => json_encode([
                    'Iihaw ang talong sa apoy hanggang maluto at malambot ang laman.',
                    'Balatan ang talong at pisilin gamit ang tinidor.',
                    'Batiin ang itlog at lagyan ng asin.',
                    'Isawsaw ang talong sa binatiing itlog.',
                    'Iprito sa mainit na mantika hanggang magkulay ginto.',
                    'Ihain na mainit kasama ng kanin.',
                ]),
                'ingredients' => [
                    ['name' => 'Talong (eggplant)', 'quantity' => 2, 'unit' => 'piece', 'estimated_cost' => 30.00],
                    ['name' => 'Eggs', 'quantity' => 3, 'unit' => 'piece', 'estimated_cost' => 24.00],
                    ['name' => 'Cooking oil', 'quantity' => 3, 'unit' => 'tbsp', 'estimated_cost' => 2.50],
                    ['name' => 'Salt (asin)', 'quantity' => 1, 'unit' => 'pinch', 'estimated_cost' => 0.50],
                ],
                'equipment' => ['Kalan', 'Kawali'],
                'dietary_flags' => ['Eggs', 'Vegan'],
            ],
            [
                'name' => 'Oatmeal na may Saging',
                'description' => 'Quick and nutritious oatmeal topped with sliced banana. A healthy modern Filipino breakfast option.',
                'meal_type' => 'almusal',
                'difficulty' => 'madali',
                'cook_time_minutes' => 10,
                'servings' => 1,
                'calories' => 220.00,
                'protein' => 6.00,
                'iron' => 2.00,
                'vitamin_c' => 5.00,
                'instructions' => json_encode([
                    'Pakuluan ang tubig o gatas sa palayok.',
                    'Ilagay ang oatmeal at haluin.',
                    'Lutuin ng 3-5 minuto sa katamtamang apoy.',
                    'Ilagay sa mangkok at lagyan ng hiwa-hiwang saging.',
                    'Pwedeng lagyan ng asukal o honey.',
                ]),
                'ingredients' => [
                    ['name' => 'Oatmeal', 'quantity' => 0.5, 'unit' => 'cup', 'estimated_cost' => 7.00],
                    ['name' => 'Sugar', 'quantity' => 1, 'unit' => 'tbsp', 'estimated_cost' => 1.00],
                ],
                'equipment' => ['Kalan', 'Palayok'],
                'dietary_flags' => ['Gluten'],
            ],

            // ===== TANGHALIAN (Lunch) =====
            [
                'name' => 'Adobong Manok',
                'description' => 'The quintessential Filipino dish - chicken braised in soy sauce, vinegar, garlic, and bay leaves. Every family has their own version.',
                'meal_type' => 'tanghalian',
                'difficulty' => 'katamtaman',
                'cook_time_minutes' => 40,
                'servings' => 4,
                'calories' => 380.00,
                'protein' => 28.00,
                'iron' => 2.00,
                'vitamin_c' => 2.00,
                'instructions' => json_encode([
                    'Pagsamahin ang manok, toyo, suka, bawang, paminta, at dahon ng laurel sa palayok.',
                    'Pakuluan at takpan. Lutuin ng 20 minuto.',
                    'Buksan ang takip at lutuin hanggang bumaba ang sabaw.',
                    'Lagyan ng asukal kung gusto ng konting tamis.',
                    'Ihain na mainit kasama ng kanin.',
                ]),
                'ingredients' => [
                    ['name' => 'Chicken thigh', 'quantity' => 0.5, 'unit' => 'kg', 'estimated_cost' => 85.00],
                    ['name' => 'Soy sauce (toyo)', 'quantity' => 0.25, 'unit' => 'cup', 'estimated_cost' => 3.00],
                    ['name' => 'Vinegar (suka)', 'quantity' => 0.25, 'unit' => 'cup', 'estimated_cost' => 2.00],
                    ['name' => 'Garlic (bawang)', 'quantity' => 8, 'unit' => 'cloves', 'estimated_cost' => 4.00],
                    ['name' => 'Bay leaves (laurel)', 'quantity' => 3, 'unit' => 'piece', 'estimated_cost' => 3.00],
                    ['name' => 'Pepper (paminta)', 'quantity' => 1, 'unit' => 'tsp', 'estimated_cost' => 0.50],
                    ['name' => 'Cooking oil', 'quantity' => 2, 'unit' => 'tbsp', 'estimated_cost' => 2.00],
                ],
                'equipment' => ['Kalan', 'Palayok'],
                'dietary_flags' => ['Soy', 'Vegan', 'Vegetarian', 'Pescatarian'],
            ],
            [
                'name' => 'Sinigang na Baboy',
                'description' => 'Tamarind-based sour soup with pork and vegetables. A refreshing and hearty Filipino classic.',
                'meal_type' => 'tanghalian',
                'difficulty' => 'katamtaman',
                'cook_time_minutes' => 45,
                'servings' => 6,
                'calories' => 320.00,
                'protein' => 22.00,
                'iron' => 2.50,
                'vitamin_c' => 25.00,
                'instructions' => json_encode([
                    'Pakuluan ang baboy sa tubig hanggang maluto. Alisin ang dumi sa ibabaw.',
                    'Ilagay ang sibuyas at kamatis. Lutuin ng 5 minuto.',
                    'Ilagay ang sinigang mix at haluin.',
                    'Ilagay ang matitigas na gulay (sitaw, talong) at lutuin ng 5 minuto.',
                    'Ilagay ang kangkong at sili. Lutuin ng 2 minuto.',
                    'Lagyan ng patis ayon sa panlasa.',
                    'Ihain na mainit kasama ng kanin.',
                ]),
                'ingredients' => [
                    ['name' => 'Pork belly (liempo)', 'quantity' => 0.5, 'unit' => 'kg', 'estimated_cost' => 140.00],
                    ['name' => 'Kangkong', 'quantity' => 1, 'unit' => 'bundle', 'estimated_cost' => 15.00],
                    ['name' => 'Sitaw (string beans)', 'quantity' => 1, 'unit' => 'bundle', 'estimated_cost' => 30.00],
                    ['name' => 'Talong (eggplant)', 'quantity' => 2, 'unit' => 'piece', 'estimated_cost' => 30.00],
                    ['name' => 'Tomatoes (kamatis)', 'quantity' => 2, 'unit' => 'piece', 'estimated_cost' => 8.00],
                    ['name' => 'Onion (sibuyas)', 'quantity' => 1, 'unit' => 'piece', 'estimated_cost' => 6.00],
                    ['name' => 'Fish sauce (patis)', 'quantity' => 2, 'unit' => 'tbsp', 'estimated_cost' => 1.50],
                ],
                'equipment' => ['Kalan', 'Palayok'],
                'dietary_flags' => ['Vegan', 'Vegetarian', 'Halal', 'Pescatarian'],
            ],
            [
                'name' => 'Ginisang Monggo',
                'description' => 'Sauteed mung beans stewed with leafy greens. A nutritious and budget-friendly Filipino staple often served on Fridays.',
                'meal_type' => 'tanghalian',
                'difficulty' => 'katamtaman',
                'cook_time_minutes' => 35,
                'servings' => 4,
                'calories' => 250.00,
                'protein' => 14.00,
                'iron' => 3.50,
                'vitamin_c' => 15.00,
                'instructions' => json_encode([
                    'Pakuluan ang monggo sa tubig hanggang lumambot (mga 20 minuto).',
                    'Sa kawali, igisa ang bawang, sibuyas, at kamatis.',
                    'Ilagay ang nilutong monggo sa ginisa.',
                    'Lagyan ng patis at haluin.',
                    'Ilagay ang malunggay o ampalaya leaves.',
                    'Lutuin ng 5 minuto pa. Ihain na mainit.',
                ]),
                'ingredients' => [
                    ['name' => 'Monggo (mung beans)', 'quantity' => 1, 'unit' => 'cup', 'estimated_cost' => 12.00],
                    ['name' => 'Malunggay leaves', 'quantity' => 1, 'unit' => 'bundle', 'estimated_cost' => 10.00],
                    ['name' => 'Tomatoes (kamatis)', 'quantity' => 2, 'unit' => 'piece', 'estimated_cost' => 8.00],
                    ['name' => 'Onion (sibuyas)', 'quantity' => 1, 'unit' => 'piece', 'estimated_cost' => 6.00],
                    ['name' => 'Garlic (bawang)', 'quantity' => 4, 'unit' => 'cloves', 'estimated_cost' => 2.00],
                    ['name' => 'Fish sauce (patis)', 'quantity' => 2, 'unit' => 'tbsp', 'estimated_cost' => 1.50],
                    ['name' => 'Cooking oil', 'quantity' => 2, 'unit' => 'tbsp', 'estimated_cost' => 2.00],
                ],
                'equipment' => ['Kalan', 'Palayok', 'Kawali'],
                'dietary_flags' => [],
            ],
            [
                'name' => 'Paksiw na Isda',
                'description' => 'Fish stewed in vinegar with ginger and garlic. A simple, tangy, and affordable everyday dish.',
                'meal_type' => 'tanghalian',
                'difficulty' => 'madali',
                'cook_time_minutes' => 20,
                'servings' => 3,
                'calories' => 200.00,
                'protein' => 24.00,
                'iron' => 1.50,
                'vitamin_c' => 3.00,
                'instructions' => json_encode([
                    'Ilagay ang isda sa palayok.',
                    'Buhusan ng suka, tubig, at patis.',
                    'Ilagay ang luya, bawang, sibuyas, at paminta.',
                    'Pakuluan at lutuin sa katamtamang apoy ng 15 minuto.',
                    'Huwag haluin para hindi madurog ang isda.',
                    'Ihain na mainit kasama ng kanin.',
                ]),
                'ingredients' => [
                    ['name' => 'Galunggong (mackerel)', 'quantity' => 0.5, 'unit' => 'kg', 'estimated_cost' => 75.00],
                    ['name' => 'Vinegar (suka)', 'quantity' => 0.25, 'unit' => 'cup', 'estimated_cost' => 2.00],
                    ['name' => 'Ginger (luya)', 'quantity' => 1, 'unit' => 'thumb', 'estimated_cost' => 1.50],
                    ['name' => 'Garlic (bawang)', 'quantity' => 4, 'unit' => 'cloves', 'estimated_cost' => 2.00],
                    ['name' => 'Onion (sibuyas)', 'quantity' => 1, 'unit' => 'piece', 'estimated_cost' => 6.00],
                    ['name' => 'Fish sauce (patis)', 'quantity' => 1, 'unit' => 'tbsp', 'estimated_cost' => 1.00],
                    ['name' => 'Pepper (paminta)', 'quantity' => 0.5, 'unit' => 'tsp', 'estimated_cost' => 0.50],
                ],
                'equipment' => ['Kalan', 'Palayok'],
                'dietary_flags' => ['Seafood', 'Vegan', 'Vegetarian'],
            ],
            [
                'name' => 'Tinolang Manok',
                'description' => 'Ginger-based chicken soup with green papaya and malunggay leaves. A nourishing and comforting Filipino classic.',
                'meal_type' => 'tanghalian',
                'difficulty' => 'katamtaman',
                'cook_time_minutes' => 35,
                'servings' => 4,
                'calories' => 280.00,
                'protein' => 25.00,
                'iron' => 2.00,
                'vitamin_c' => 30.00,
                'instructions' => json_encode([
                    'Igisa ang bawang, sibuyas, at luya sa mantika.',
                    'Ilagay ang manok at igisa hanggang mag-iba kulay.',
                    'Buhusan ng tubig at pakuluan.',
                    'Ilagay ang sayote o papaya. Lutuin ng 10 minuto.',
                    'Ilagay ang malunggay leaves at lutuin ng 2 minuto.',
                    'Lagyan ng patis ayon sa panlasa.',
                    'Ihain na mainit.',
                ]),
                'ingredients' => [
                    ['name' => 'Chicken (whole)', 'quantity' => 0.5, 'unit' => 'kg', 'estimated_cost' => 90.00],
                    ['name' => 'Sayote (chayote)', 'quantity' => 1, 'unit' => 'piece', 'estimated_cost' => 20.00],
                    ['name' => 'Malunggay leaves', 'quantity' => 1, 'unit' => 'bundle', 'estimated_cost' => 10.00],
                    ['name' => 'Ginger (luya)', 'quantity' => 1, 'unit' => 'thumb', 'estimated_cost' => 1.50],
                    ['name' => 'Onion (sibuyas)', 'quantity' => 1, 'unit' => 'piece', 'estimated_cost' => 6.00],
                    ['name' => 'Garlic (bawang)', 'quantity' => 3, 'unit' => 'cloves', 'estimated_cost' => 1.50],
                    ['name' => 'Fish sauce (patis)', 'quantity' => 2, 'unit' => 'tbsp', 'estimated_cost' => 1.50],
                    ['name' => 'Cooking oil', 'quantity' => 1, 'unit' => 'tbsp', 'estimated_cost' => 1.00],
                ],
                'equipment' => ['Kalan', 'Palayok'],
                'dietary_flags' => ['Vegan', 'Vegetarian', 'Pescatarian'],
            ],
            [
                'name' => 'Ginisang Pechay',
                'description' => 'Quick sauteed bok choy with garlic and oyster sauce. A simple vegetable side dish ready in minutes.',
                'meal_type' => 'tanghalian',
                'difficulty' => 'madali',
                'cook_time_minutes' => 10,
                'servings' => 2,
                'calories' => 80.00,
                'protein' => 3.00,
                'iron' => 1.50,
                'vitamin_c' => 20.00,
                'instructions' => json_encode([
                    'Magpainit ng mantika sa kawali.',
                    'Igisa ang bawang hanggang mabango.',
                    'Ilagay ang pechay at haluin ng mabilis.',
                    'Lagyan ng oyster sauce at konting tubig.',
                    'Lutuin ng 2-3 minuto. Huwag sobrang luto.',
                    'Ihain agad.',
                ]),
                'ingredients' => [
                    ['name' => 'Pechay', 'quantity' => 2, 'unit' => 'bundle', 'estimated_cost' => 40.00],
                    ['name' => 'Garlic (bawang)', 'quantity' => 4, 'unit' => 'cloves', 'estimated_cost' => 2.00],
                    ['name' => 'Oyster sauce', 'quantity' => 2, 'unit' => 'tbsp', 'estimated_cost' => 3.00],
                    ['name' => 'Cooking oil', 'quantity' => 1, 'unit' => 'tbsp', 'estimated_cost' => 1.00],
                ],
                'equipment' => ['Kalan', 'Kawali'],
                'dietary_flags' => [],
            ],
            [
                'name' => 'Pinakbet',
                'description' => 'Mixed vegetables stewed in shrimp paste. An Ilocano classic featuring bitter gourd, squash, eggplant, and more.',
                'meal_type' => 'tanghalian',
                'difficulty' => 'katamtaman',
                'cook_time_minutes' => 30,
                'servings' => 4,
                'calories' => 180.00,
                'protein' => 8.00,
                'iron' => 2.50,
                'vitamin_c' => 35.00,
                'instructions' => json_encode([
                    'Igisa ang bawang, sibuyas, at kamatis.',
                    'Ilagay ang bagoong o patis at haluin.',
                    'Ilagay ang kalabasa at lutuin ng 5 minuto.',
                    'Idagdag ang ampalaya, talong, sitaw, at okra.',
                    'Takpan at lutuin ng 10-15 minuto sa katamtamang apoy.',
                    'Huwag masyadong haluin para hindi madurog ang gulay.',
                    'Ihain na mainit kasama ng kanin.',
                ]),
                'ingredients' => [
                    ['name' => 'Kalabasa (squash)', 'quantity' => 0.25, 'unit' => 'kg', 'estimated_cost' => 10.00],
                    ['name' => 'Ampalaya (bitter gourd)', 'quantity' => 1, 'unit' => 'piece', 'estimated_cost' => 30.00],
                    ['name' => 'Talong (eggplant)', 'quantity' => 2, 'unit' => 'piece', 'estimated_cost' => 30.00],
                    ['name' => 'Sitaw (string beans)', 'quantity' => 1, 'unit' => 'bundle', 'estimated_cost' => 30.00],
                    ['name' => 'Tomatoes (kamatis)', 'quantity' => 2, 'unit' => 'piece', 'estimated_cost' => 8.00],
                    ['name' => 'Onion (sibuyas)', 'quantity' => 1, 'unit' => 'piece', 'estimated_cost' => 6.00],
                    ['name' => 'Garlic (bawang)', 'quantity' => 4, 'unit' => 'cloves', 'estimated_cost' => 2.00],
                    ['name' => 'Fish sauce (patis)', 'quantity' => 2, 'unit' => 'tbsp', 'estimated_cost' => 1.50],
                    ['name' => 'Cooking oil', 'quantity' => 2, 'unit' => 'tbsp', 'estimated_cost' => 2.00],
                ],
                'equipment' => ['Kalan', 'Palayok'],
                'dietary_flags' => [],
            ],
            [
                'name' => 'Mechado',
                'description' => 'Filipino beef stew braised in tomato sauce with potatoes and carrots. A hearty and filling lunch dish.',
                'meal_type' => 'tanghalian',
                'difficulty' => 'mahirap',
                'cook_time_minutes' => 60,
                'servings' => 5,
                'calories' => 420.00,
                'protein' => 30.00,
                'iron' => 4.00,
                'vitamin_c' => 15.00,
                'instructions' => json_encode([
                    'Igisa ang bawang at sibuyas sa mantika.',
                    'Ilagay ang baka at igisa hanggang mag-iba kulay.',
                    'Lagyan ng toyo at tomato sauce.',
                    'Buhusan ng tubig at pakuluan. Lutuin ng 40 minuto sa mahinang apoy.',
                    'Ilagay ang patatas at karot. Lutuin ng 15 minuto pa.',
                    'Lagyan ng asin at paminta ayon sa panlasa.',
                    'Ihain na mainit kasama ng kanin.',
                ]),
                'ingredients' => [
                    ['name' => 'Beef (brisket)', 'quantity' => 0.5, 'unit' => 'kg', 'estimated_cost' => 175.00],
                    ['name' => 'Potatoes', 'quantity' => 2, 'unit' => 'piece', 'estimated_cost' => 21.00],
                    ['name' => 'Carrots', 'quantity' => 1, 'unit' => 'piece', 'estimated_cost' => 6.00],
                    ['name' => 'Tomatoes (kamatis)', 'quantity' => 3, 'unit' => 'piece', 'estimated_cost' => 12.00],
                    ['name' => 'Onion (sibuyas)', 'quantity' => 1, 'unit' => 'piece', 'estimated_cost' => 6.00],
                    ['name' => 'Garlic (bawang)', 'quantity' => 5, 'unit' => 'cloves', 'estimated_cost' => 2.50],
                    ['name' => 'Soy sauce (toyo)', 'quantity' => 3, 'unit' => 'tbsp', 'estimated_cost' => 2.00],
                    ['name' => 'Cooking oil', 'quantity' => 2, 'unit' => 'tbsp', 'estimated_cost' => 2.00],
                    ['name' => 'Salt (asin)', 'quantity' => 1, 'unit' => 'tsp', 'estimated_cost' => 0.50],
                    ['name' => 'Pepper (paminta)', 'quantity' => 0.5, 'unit' => 'tsp', 'estimated_cost' => 0.50],
                ],
                'equipment' => ['Kalan', 'Palayok'],
                'dietary_flags' => ['Soy', 'Vegan', 'Vegetarian', 'Halal', 'Pescatarian'],
            ],

            // ===== MERIENDA (Snack) =====
            [
                'name' => 'Turon',
                'description' => 'Crispy banana spring rolls coated in caramelized sugar. A beloved Filipino street food snack.',
                'meal_type' => 'merienda',
                'difficulty' => 'katamtaman',
                'cook_time_minutes' => 25,
                'servings' => 6,
                'calories' => 200.00,
                'protein' => 2.00,
                'iron' => 0.50,
                'vitamin_c' => 5.00,
                'instructions' => json_encode([
                    'Balutan ang saging at langka sa lumpia wrapper.',
                    'Idikit ang dulo gamit ang tubig.',
                    'Magpainit ng mantika sa kawali.',
                    'Iprito ang turon hanggang gumintong kulay.',
                    'Budburan ng asukal habang nagpiprito para mag-caramelize.',
                    'Patunugin sa papel at ihain.',
                ]),
                'ingredients' => [
                    ['name' => 'Sugar', 'quantity' => 0.5, 'unit' => 'cup', 'estimated_cost' => 5.50],
                    ['name' => 'Cooking oil', 'quantity' => 2, 'unit' => 'cups', 'estimated_cost' => 27.00],
                ],
                'equipment' => ['Kalan', 'Kawali'],
                'dietary_flags' => [],
            ],
            [
                'name' => 'Kamote Cue',
                'description' => 'Deep-fried sweet potato coated in caramelized brown sugar. A popular and affordable street food snack.',
                'meal_type' => 'merienda',
                'difficulty' => 'madali',
                'cook_time_minutes' => 15,
                'servings' => 4,
                'calories' => 250.00,
                'protein' => 2.00,
                'iron' => 0.80,
                'vitamin_c' => 10.00,
                'instructions' => json_encode([
                    'Hiwain ang kamote ng pahilis, mga 1 inch ang kapal.',
                    'Magpainit ng mantika sa kawali.',
                    'Iprito ang kamote hanggang maluto at magkulay ginto.',
                    'Budburan ng brown sugar at hayaang mag-caramelize.',
                    'Tusukan ng barbecue stick at ihain.',
                ]),
                'ingredients' => [
                    ['name' => 'Kamote (sweet potato)', 'quantity' => 0.5, 'unit' => 'kg', 'estimated_cost' => 17.50],
                    ['name' => 'Sugar', 'quantity' => 0.5, 'unit' => 'cup', 'estimated_cost' => 5.50],
                    ['name' => 'Cooking oil', 'quantity' => 2, 'unit' => 'cups', 'estimated_cost' => 27.00],
                ],
                'equipment' => ['Kalan', 'Kawali'],
                'dietary_flags' => [],
            ],
            [
                'name' => 'Banana Cue',
                'description' => 'Deep-fried saba banana coated in caramelized brown sugar. A classic Filipino merienda sold on street corners.',
                'meal_type' => 'merienda',
                'difficulty' => 'madali',
                'cook_time_minutes' => 15,
                'servings' => 4,
                'calories' => 280.00,
                'protein' => 1.50,
                'iron' => 0.50,
                'vitamin_c' => 8.00,
                'instructions' => json_encode([
                    'Magpainit ng mantika sa kawali.',
                    'Iprito ang saging na saba hanggang gumintong kulay.',
                    'Budburan ng brown sugar at hayaang mag-caramelize.',
                    'Baliktarin para pantay ang coating.',
                    'Tusukan ng barbecue stick at ihain.',
                ]),
                'ingredients' => [
                    ['name' => 'Sugar', 'quantity' => 0.5, 'unit' => 'cup', 'estimated_cost' => 5.50],
                    ['name' => 'Cooking oil', 'quantity' => 2, 'unit' => 'cups', 'estimated_cost' => 27.00],
                ],
                'equipment' => ['Kalan', 'Kawali'],
                'dietary_flags' => [],
            ],
            [
                'name' => 'Pancit Canton',
                'description' => 'Stir-fried egg noodles with vegetables and soy sauce. A quick and filling Filipino noodle dish.',
                'meal_type' => 'merienda',
                'difficulty' => 'madali',
                'cook_time_minutes' => 15,
                'servings' => 3,
                'calories' => 320.00,
                'protein' => 10.00,
                'iron' => 2.00,
                'vitamin_c' => 12.00,
                'instructions' => json_encode([
                    'Igisa ang bawang, sibuyas, at karot sa mantika.',
                    'Ilagay ang repolyo at lutuin ng 2 minuto.',
                    'Ilagay ang pancit canton noodles.',
                    'Buhusan ng toyo, oyster sauce, at konting tubig.',
                    'Haluin hanggang maluto ang noodles at matuyo ang sabaw.',
                    'Lagyan ng kalamansi at ihain.',
                ]),
                'ingredients' => [
                    ['name' => 'Pancit canton noodles', 'quantity' => 2, 'unit' => 'pack', 'estimated_cost' => 24.00],
                    ['name' => 'Cabbage (repolyo)', 'quantity' => 0.25, 'unit' => 'head', 'estimated_cost' => 12.50],
                    ['name' => 'Carrots', 'quantity' => 1, 'unit' => 'piece', 'estimated_cost' => 6.00],
                    ['name' => 'Onion (sibuyas)', 'quantity' => 1, 'unit' => 'piece', 'estimated_cost' => 6.00],
                    ['name' => 'Garlic (bawang)', 'quantity' => 4, 'unit' => 'cloves', 'estimated_cost' => 2.00],
                    ['name' => 'Soy sauce (toyo)', 'quantity' => 2, 'unit' => 'tbsp', 'estimated_cost' => 1.50],
                    ['name' => 'Oyster sauce', 'quantity' => 1, 'unit' => 'tbsp', 'estimated_cost' => 1.50],
                    ['name' => 'Calamansi', 'quantity' => 4, 'unit' => 'piece', 'estimated_cost' => 20.00],
                    ['name' => 'Cooking oil', 'quantity' => 2, 'unit' => 'tbsp', 'estimated_cost' => 2.00],
                ],
                'equipment' => ['Kalan', 'Kawali'],
                'dietary_flags' => ['Gluten', 'Soy'],
            ],
            [
                'name' => 'Arroz Caldo',
                'description' => 'Filipino chicken and rice soup flavored with ginger and garlic. A warm, comforting congee-style dish.',
                'meal_type' => 'merienda',
                'difficulty' => 'katamtaman',
                'cook_time_minutes' => 30,
                'servings' => 4,
                'calories' => 300.00,
                'protein' => 18.00,
                'iron' => 1.50,
                'vitamin_c' => 2.00,
                'instructions' => json_encode([
                    'Igisa ang bawang, sibuyas, at luya sa mantika.',
                    'Ilagay ang manok at igisa ng 5 minuto.',
                    'Ilagay ang bigas at haluin ng 2 minuto.',
                    'Buhusan ng tubig at patis. Pakuluan.',
                    'Lutuin sa mahinang apoy ng 20 minuto, hinahalo paminsan-minsan.',
                    'Ihain na mainit na may tokwa, sibuyas na mura, at kalamansi.',
                ]),
                'ingredients' => [
                    ['name' => 'Chicken thigh', 'quantity' => 0.25, 'unit' => 'kg', 'estimated_cost' => 42.50],
                    ['name' => 'Rice (bigas)', 'quantity' => 1, 'unit' => 'cup', 'estimated_cost' => 8.00],
                    ['name' => 'Ginger (luya)', 'quantity' => 1, 'unit' => 'thumb', 'estimated_cost' => 1.50],
                    ['name' => 'Garlic (bawang)', 'quantity' => 5, 'unit' => 'cloves', 'estimated_cost' => 2.50],
                    ['name' => 'Onion (sibuyas)', 'quantity' => 1, 'unit' => 'piece', 'estimated_cost' => 6.00],
                    ['name' => 'Fish sauce (patis)', 'quantity' => 2, 'unit' => 'tbsp', 'estimated_cost' => 1.50],
                    ['name' => 'Cooking oil', 'quantity' => 1, 'unit' => 'tbsp', 'estimated_cost' => 1.00],
                    ['name' => 'Calamansi', 'quantity' => 4, 'unit' => 'piece', 'estimated_cost' => 20.00],
                ],
                'equipment' => ['Kalan', 'Palayok'],
                'dietary_flags' => ['Vegan', 'Vegetarian', 'Pescatarian'],
            ],
            [
                'name' => 'Mais con Yelo',
                'description' => 'Sweet corn shaved ice dessert with milk. A refreshing Filipino summer treat that is easy to make.',
                'meal_type' => 'merienda',
                'difficulty' => 'madali',
                'cook_time_minutes' => 10,
                'servings' => 2,
                'calories' => 180.00,
                'protein' => 4.00,
                'iron' => 0.30,
                'vitamin_c' => 3.00,
                'instructions' => json_encode([
                    'Ilagay ang sweet corn kernels sa baso.',
                    'Lagyan ng yelo na kinaskas.',
                    'Buhusan ng evaporated milk.',
                    'Lagyan ng asukal ayon sa panlasa.',
                    'Haluin at ihain agad.',
                ]),
                'ingredients' => [
                    ['name' => 'Sugar', 'quantity' => 2, 'unit' => 'tbsp', 'estimated_cost' => 1.50],
                ],
                'equipment' => ['Ref'],
                'dietary_flags' => ['Dairy'],
            ],

            // ===== HAPUNAN (Dinner) =====
            [
                'name' => 'Ginataang Kalabasa',
                'description' => 'Squash simmered in rich coconut milk. A creamy, mildly sweet vegetable dish perfect for dinner.',
                'meal_type' => 'hapunan',
                'difficulty' => 'katamtaman',
                'cook_time_minutes' => 30,
                'servings' => 4,
                'calories' => 220.00,
                'protein' => 5.00,
                'iron' => 1.50,
                'vitamin_c' => 12.00,
                'instructions' => json_encode([
                    'Igisa ang bawang, sibuyas sa mantika.',
                    'Ilagay ang kalabasa at haluin.',
                    'Buhusan ng gata at pakuluan.',
                    'Lutuin sa mahinang apoy ng 15-20 minuto hanggang maluto ang kalabasa.',
                    'Lagyan ng patis at paminta ayon sa panlasa.',
                    'Ilagay ang sitaw kung gusto. Lutuin ng 3 minuto pa.',
                    'Ihain na mainit kasama ng kanin.',
                ]),
                'ingredients' => [
                    ['name' => 'Kalabasa (squash)', 'quantity' => 0.5, 'unit' => 'kg', 'estimated_cost' => 20.00],
                    ['name' => 'Coconut milk (gata)', 'quantity' => 1, 'unit' => 'can', 'estimated_cost' => 35.00],
                    ['name' => 'Sitaw (string beans)', 'quantity' => 1, 'unit' => 'bundle', 'estimated_cost' => 30.00],
                    ['name' => 'Onion (sibuyas)', 'quantity' => 1, 'unit' => 'piece', 'estimated_cost' => 6.00],
                    ['name' => 'Garlic (bawang)', 'quantity' => 3, 'unit' => 'cloves', 'estimated_cost' => 1.50],
                    ['name' => 'Fish sauce (patis)', 'quantity' => 1, 'unit' => 'tbsp', 'estimated_cost' => 1.00],
                    ['name' => 'Cooking oil', 'quantity' => 1, 'unit' => 'tbsp', 'estimated_cost' => 1.00],
                ],
                'equipment' => ['Kalan', 'Palayok'],
                'dietary_flags' => [],
            ],
            [
                'name' => 'Tortang Giniling',
                'description' => 'Filipino-style omelette with seasoned ground pork. A quick and protein-rich dinner option.',
                'meal_type' => 'hapunan',
                'difficulty' => 'madali',
                'cook_time_minutes' => 15,
                'servings' => 3,
                'calories' => 350.00,
                'protein' => 22.00,
                'iron' => 2.50,
                'vitamin_c' => 5.00,
                'instructions' => json_encode([
                    'Igisa ang bawang at sibuyas.',
                    'Ilagay ang giniling na baboy at lutuin hanggang mag-iba kulay.',
                    'Lagyan ng toyo, asin, at paminta.',
                    'Hayaang lumamig ng konti ang giniling.',
                    'Ihalo ang giniling sa binatiing itlog.',
                    'Iprito sa kawali hanggang magkulay ginto sa magkabilang panig.',
                    'Ihain kasama ng kanin at ketchup.',
                ]),
                'ingredients' => [
                    ['name' => 'Ground pork', 'quantity' => 0.25, 'unit' => 'kg', 'estimated_cost' => 55.00],
                    ['name' => 'Eggs', 'quantity' => 3, 'unit' => 'piece', 'estimated_cost' => 24.00],
                    ['name' => 'Onion (sibuyas)', 'quantity' => 1, 'unit' => 'piece', 'estimated_cost' => 6.00],
                    ['name' => 'Garlic (bawang)', 'quantity' => 3, 'unit' => 'cloves', 'estimated_cost' => 1.50],
                    ['name' => 'Soy sauce (toyo)', 'quantity' => 1, 'unit' => 'tbsp', 'estimated_cost' => 1.00],
                    ['name' => 'Cooking oil', 'quantity' => 3, 'unit' => 'tbsp', 'estimated_cost' => 2.50],
                    ['name' => 'Salt (asin)', 'quantity' => 1, 'unit' => 'pinch', 'estimated_cost' => 0.50],
                    ['name' => 'Pepper (paminta)', 'quantity' => 1, 'unit' => 'pinch', 'estimated_cost' => 0.50],
                ],
                'equipment' => ['Kalan', 'Kawali'],
                'dietary_flags' => ['Eggs', 'Soy', 'Vegan', 'Vegetarian', 'Halal', 'Pescatarian'],
            ],
            [
                'name' => 'Nilagang Baboy',
                'description' => 'Simple boiled pork soup with vegetables. A clear, comforting broth dish perfect for family dinners.',
                'meal_type' => 'hapunan',
                'difficulty' => 'katamtaman',
                'cook_time_minutes' => 45,
                'servings' => 5,
                'calories' => 350.00,
                'protein' => 24.00,
                'iron' => 2.00,
                'vitamin_c' => 20.00,
                'instructions' => json_encode([
                    'Pakuluan ang baboy sa tubig. Alisin ang dumi.',
                    'Ilagay ang sibuyas at bawang. Lutuin ng 30 minuto.',
                    'Ilagay ang patatas, kamote, at repolyo.',
                    'Lutuin ng 10 minuto hanggang maluto ang gulay.',
                    'Ilagay ang pechay at sili. Lutuin ng 2 minuto.',
                    'Lagyan ng patis at paminta.',
                    'Ihain na mainit kasama ng kanin at patis na may kalamansi.',
                ]),
                'ingredients' => [
                    ['name' => 'Pork shoulder (kasim)', 'quantity' => 0.5, 'unit' => 'kg', 'estimated_cost' => 125.00],
                    ['name' => 'Potatoes', 'quantity' => 2, 'unit' => 'piece', 'estimated_cost' => 21.00],
                    ['name' => 'Cabbage (repolyo)', 'quantity' => 0.25, 'unit' => 'head', 'estimated_cost' => 12.50],
                    ['name' => 'Pechay', 'quantity' => 1, 'unit' => 'bundle', 'estimated_cost' => 20.00],
                    ['name' => 'Onion (sibuyas)', 'quantity' => 1, 'unit' => 'piece', 'estimated_cost' => 6.00],
                    ['name' => 'Fish sauce (patis)', 'quantity' => 2, 'unit' => 'tbsp', 'estimated_cost' => 1.50],
                    ['name' => 'Pepper (paminta)', 'quantity' => 1, 'unit' => 'tsp', 'estimated_cost' => 0.50],
                ],
                'equipment' => ['Kalan', 'Palayok'],
                'dietary_flags' => ['Vegan', 'Vegetarian', 'Halal', 'Pescatarian'],
            ],
            [
                'name' => 'Bistek Tagalog',
                'description' => 'Filipino beef steak marinated in soy sauce and calamansi, topped with onion rings. A flavorful and savory dinner dish.',
                'meal_type' => 'hapunan',
                'difficulty' => 'katamtaman',
                'cook_time_minutes' => 30,
                'servings' => 3,
                'calories' => 400.00,
                'protein' => 28.00,
                'iron' => 3.50,
                'vitamin_c' => 8.00,
                'instructions' => json_encode([
                    'Ibabad ang baka sa toyo at kalamansi ng 30 minuto.',
                    'Iprito ang baka sa mainit na mantika hanggang maluto. Itabi.',
                    'Sa parehong kawali, igisa ang sibuyas na bilog.',
                    'Ibalik ang baka at buhusan ng marinada.',
                    'Lutuin ng 5 minuto sa katamtamang apoy.',
                    'Ihain na mainit kasama ng kanin.',
                ]),
                'ingredients' => [
                    ['name' => 'Beef (brisket)', 'quantity' => 0.3, 'unit' => 'kg', 'estimated_cost' => 105.00],
                    ['name' => 'Soy sauce (toyo)', 'quantity' => 0.25, 'unit' => 'cup', 'estimated_cost' => 3.00],
                    ['name' => 'Calamansi', 'quantity' => 6, 'unit' => 'piece', 'estimated_cost' => 30.00],
                    ['name' => 'Onion (sibuyas)', 'quantity' => 2, 'unit' => 'piece', 'estimated_cost' => 12.00],
                    ['name' => 'Cooking oil', 'quantity' => 3, 'unit' => 'tbsp', 'estimated_cost' => 2.50],
                    ['name' => 'Pepper (paminta)', 'quantity' => 0.5, 'unit' => 'tsp', 'estimated_cost' => 0.50],
                ],
                'equipment' => ['Kalan', 'Kawali'],
                'dietary_flags' => ['Soy', 'Vegan', 'Vegetarian', 'Halal', 'Pescatarian'],
            ],
            [
                'name' => 'Kare-Kare',
                'description' => 'Rich peanut-based stew with oxtail and vegetables. A festive Filipino dish traditionally served with bagoong.',
                'meal_type' => 'hapunan',
                'difficulty' => 'mahirap',
                'cook_time_minutes' => 60,
                'servings' => 6,
                'calories' => 450.00,
                'protein' => 30.00,
                'iron' => 4.00,
                'vitamin_c' => 10.00,
                'instructions' => json_encode([
                    'Pakuluan ang baka sa tubig ng 45 minuto hanggang lumambot.',
                    'Sa kawali, igisa ang bawang at sibuyas.',
                    'Ilagay ang peanut butter at haluin.',
                    'Buhusan ng sabaw mula sa nilutong baka.',
                    'Ilagay ang baka at haluin.',
                    'Ilagay ang talong, sitaw, at pechay.',
                    'Lutuin ng 10 minuto hanggang maluto ang gulay.',
                    'Ihain kasama ng bagoong at kanin.',
                ]),
                'ingredients' => [
                    ['name' => 'Beef (brisket)', 'quantity' => 0.5, 'unit' => 'kg', 'estimated_cost' => 175.00],
                    ['name' => 'Peanut butter', 'quantity' => 0.5, 'unit' => 'cup', 'estimated_cost' => 16.00],
                    ['name' => 'Talong (eggplant)', 'quantity' => 2, 'unit' => 'piece', 'estimated_cost' => 30.00],
                    ['name' => 'Sitaw (string beans)', 'quantity' => 1, 'unit' => 'bundle', 'estimated_cost' => 30.00],
                    ['name' => 'Pechay', 'quantity' => 1, 'unit' => 'bundle', 'estimated_cost' => 20.00],
                    ['name' => 'Onion (sibuyas)', 'quantity' => 1, 'unit' => 'piece', 'estimated_cost' => 6.00],
                    ['name' => 'Garlic (bawang)', 'quantity' => 4, 'unit' => 'cloves', 'estimated_cost' => 2.00],
                    ['name' => 'Cooking oil', 'quantity' => 2, 'unit' => 'tbsp', 'estimated_cost' => 2.00],
                ],
                'equipment' => ['Kalan', 'Palayok', 'Kawali'],
                'dietary_flags' => ['Nuts', 'Vegan', 'Vegetarian', 'Halal', 'Pescatarian'],
            ],
            [
                'name' => 'Inihaw na Tilapia',
                'description' => 'Grilled tilapia stuffed with tomatoes, onions, and ginger. A healthy and flavorful fish dish.',
                'meal_type' => 'hapunan',
                'difficulty' => 'katamtaman',
                'cook_time_minutes' => 25,
                'servings' => 2,
                'calories' => 200.00,
                'protein' => 30.00,
                'iron' => 1.50,
                'vitamin_c' => 10.00,
                'instructions' => json_encode([
                    'Linisin ang tilapia at lagyan ng hiwa sa gilid.',
                    'Lagyan ng asin at kalamansi sa loob at labas.',
                    'Punuin ang tiyan ng kamatis, sibuyas, at luya.',
                    'Balutan ng aluminum foil o dahon ng saging.',
                    'Iihaw sa uling o kalan ng 10-12 minuto bawat panig.',
                    'Ihain kasama ng kanin at sawsawan na toyo at kalamansi.',
                ]),
                'ingredients' => [
                    ['name' => 'Tilapia', 'quantity' => 2, 'unit' => 'piece', 'estimated_cost' => 60.00],
                    ['name' => 'Tomatoes (kamatis)', 'quantity' => 2, 'unit' => 'piece', 'estimated_cost' => 8.00],
                    ['name' => 'Onion (sibuyas)', 'quantity' => 1, 'unit' => 'piece', 'estimated_cost' => 6.00],
                    ['name' => 'Ginger (luya)', 'quantity' => 1, 'unit' => 'thumb', 'estimated_cost' => 1.50],
                    ['name' => 'Calamansi', 'quantity' => 4, 'unit' => 'piece', 'estimated_cost' => 20.00],
                    ['name' => 'Salt (asin)', 'quantity' => 1, 'unit' => 'tsp', 'estimated_cost' => 0.50],
                ],
                'equipment' => ['Kalan', 'Lutuan sa Uling'],
                'dietary_flags' => ['Seafood', 'Vegan', 'Vegetarian'],
            ],
            [
                'name' => 'Ginisang Sardinas',
                'description' => 'Canned sardines sauteed with tomatoes and onions. An ultra-budget Filipino dinner ready in minutes.',
                'meal_type' => 'hapunan',
                'difficulty' => 'madali',
                'cook_time_minutes' => 10,
                'servings' => 2,
                'calories' => 250.00,
                'protein' => 18.00,
                'iron' => 2.50,
                'vitamin_c' => 10.00,
                'instructions' => json_encode([
                    'Igisa ang bawang at sibuyas sa mantika.',
                    'Ilagay ang kamatis at lutuin ng 2 minuto.',
                    'Ilagay ang sardinas kasama ang sarsa.',
                    'Haluin ng dahan-dahan para hindi madurog.',
                    'Lutuin ng 3-5 minuto.',
                    'Ihain na mainit kasama ng kanin.',
                ]),
                'ingredients' => [
                    ['name' => 'Sardines (canned)', 'quantity' => 2, 'unit' => 'can', 'estimated_cost' => 36.00],
                    ['name' => 'Tomatoes (kamatis)', 'quantity' => 2, 'unit' => 'piece', 'estimated_cost' => 8.00],
                    ['name' => 'Onion (sibuyas)', 'quantity' => 1, 'unit' => 'piece', 'estimated_cost' => 6.00],
                    ['name' => 'Garlic (bawang)', 'quantity' => 3, 'unit' => 'cloves', 'estimated_cost' => 1.50],
                    ['name' => 'Cooking oil', 'quantity' => 1, 'unit' => 'tbsp', 'estimated_cost' => 1.00],
                ],
                'equipment' => ['Kalan', 'Kawali'],
                'dietary_flags' => ['Seafood', 'Vegan', 'Vegetarian'],
            ],
            [
                'name' => 'Chopsuey',
                'description' => 'Filipino-Chinese mixed vegetable stir-fry with oyster sauce. A colorful and nutritious dinner option.',
                'meal_type' => 'hapunan',
                'difficulty' => 'katamtaman',
                'cook_time_minutes' => 20,
                'servings' => 4,
                'calories' => 200.00,
                'protein' => 8.00,
                'iron' => 2.00,
                'vitamin_c' => 30.00,
                'instructions' => json_encode([
                    'Igisa ang bawang at sibuyas sa mantika.',
                    'Ilagay ang karot at lutuin ng 3 minuto.',
                    'Idagdag ang repolyo, sitaw, at sayote.',
                    'Lagyan ng oyster sauce, toyo, at konting tubig.',
                    'Lutuin ng 5-7 minuto sa malakas na apoy.',
                    'Lagyan ng cornstarch na hinaluan ng tubig para lumapot ang sarsa.',
                    'Ihain na mainit kasama ng kanin.',
                ]),
                'ingredients' => [
                    ['name' => 'Cabbage (repolyo)', 'quantity' => 0.25, 'unit' => 'head', 'estimated_cost' => 12.50],
                    ['name' => 'Carrots', 'quantity' => 1, 'unit' => 'piece', 'estimated_cost' => 6.00],
                    ['name' => 'Sayote (chayote)', 'quantity' => 1, 'unit' => 'piece', 'estimated_cost' => 20.00],
                    ['name' => 'Sitaw (string beans)', 'quantity' => 0.5, 'unit' => 'bundle', 'estimated_cost' => 15.00],
                    ['name' => 'Onion (sibuyas)', 'quantity' => 1, 'unit' => 'piece', 'estimated_cost' => 6.00],
                    ['name' => 'Garlic (bawang)', 'quantity' => 4, 'unit' => 'cloves', 'estimated_cost' => 2.00],
                    ['name' => 'Oyster sauce', 'quantity' => 2, 'unit' => 'tbsp', 'estimated_cost' => 3.00],
                    ['name' => 'Soy sauce (toyo)', 'quantity' => 1, 'unit' => 'tbsp', 'estimated_cost' => 1.00],
                    ['name' => 'Cornstarch', 'quantity' => 1, 'unit' => 'tbsp', 'estimated_cost' => 1.00],
                    ['name' => 'Cooking oil', 'quantity' => 2, 'unit' => 'tbsp', 'estimated_cost' => 2.00],
                ],
                'equipment' => ['Kalan', 'Kawali'],
                'dietary_flags' => ['Soy'],
            ],
            [
                'name' => 'Laing',
                'description' => 'Dried taro leaves slowly cooked in thick coconut milk with chili. A spicy Bicolano specialty.',
                'meal_type' => 'hapunan',
                'difficulty' => 'mahirap',
                'cook_time_minutes' => 45,
                'servings' => 4,
                'calories' => 280.00,
                'protein' => 6.00,
                'iron' => 2.00,
                'vitamin_c' => 8.00,
                'instructions' => json_encode([
                    'Ilagay ang gata sa palayok at pakuluan.',
                    'Ilagay ang bawang, sibuyas, luya, at sili.',
                    'Ilagay ang tuyong dahon ng gabi.',
                    'Lutuin sa mahinang apoy ng 30-40 minuto.',
                    'HUWAG haluin hanggang hindi pa naluluto ng buo para hindi makati.',
                    'Lagyan ng patis ayon sa panlasa.',
                    'Ihain na mainit kasama ng kanin.',
                ]),
                'ingredients' => [
                    ['name' => 'Coconut milk (gata)', 'quantity' => 2, 'unit' => 'can', 'estimated_cost' => 70.00],
                    ['name' => 'Ginger (luya)', 'quantity' => 1, 'unit' => 'thumb', 'estimated_cost' => 1.50],
                    ['name' => 'Garlic (bawang)', 'quantity' => 5, 'unit' => 'cloves', 'estimated_cost' => 2.50],
                    ['name' => 'Onion (sibuyas)', 'quantity' => 1, 'unit' => 'piece', 'estimated_cost' => 6.00],
                    ['name' => 'Fish sauce (patis)', 'quantity' => 2, 'unit' => 'tbsp', 'estimated_cost' => 1.50],
                ],
                'equipment' => ['Kalan', 'Palayok'],
                'dietary_flags' => [],
            ],
            [
                'name' => 'Misua Soup with Patola',
                'description' => 'Light and comforting thin noodle soup with sponge gourd. A gentle dinner option that is easy to digest.',
                'meal_type' => 'hapunan',
                'difficulty' => 'madali',
                'cook_time_minutes' => 20,
                'servings' => 3,
                'calories' => 180.00,
                'protein' => 12.00,
                'iron' => 1.50,
                'vitamin_c' => 8.00,
                'instructions' => json_encode([
                    'Igisa ang bawang at sibuyas sa mantika.',
                    'Buhusan ng tubig at pakuluan.',
                    'Ilagay ang ground pork na ginawang bolitas.',
                    'Lutuin ng 5 minuto hanggang maluto ang bolitas.',
                    'Ilagay ang misua noodles at haluin.',
                    'Lagyan ng patis at paminta.',
                    'Lutuin ng 2 minuto lang (madaling maluto ang misua).',
                    'Ihain na mainit.',
                ]),
                'ingredients' => [
                    ['name' => 'Misua noodles', 'quantity' => 1, 'unit' => 'pack', 'estimated_cost' => 25.00],
                    ['name' => 'Ground pork', 'quantity' => 0.15, 'unit' => 'kg', 'estimated_cost' => 33.00],
                    ['name' => 'Garlic (bawang)', 'quantity' => 4, 'unit' => 'cloves', 'estimated_cost' => 2.00],
                    ['name' => 'Onion (sibuyas)', 'quantity' => 1, 'unit' => 'piece', 'estimated_cost' => 6.00],
                    ['name' => 'Fish sauce (patis)', 'quantity' => 2, 'unit' => 'tbsp', 'estimated_cost' => 1.50],
                    ['name' => 'Cooking oil', 'quantity' => 1, 'unit' => 'tbsp', 'estimated_cost' => 1.00],
                    ['name' => 'Pepper (paminta)', 'quantity' => 0.5, 'unit' => 'tsp', 'estimated_cost' => 0.50],
                ],
                'equipment' => ['Kalan', 'Palayok'],
                'dietary_flags' => ['Gluten', 'Vegan', 'Vegetarian', 'Halal', 'Pescatarian'],
            ],
        ];

        foreach ($recipes as $recipeData) {
            $recipeIngredients = $recipeData['ingredients'];
            $recipeEquipment = $recipeData['equipment'];
            $recipeDietaryFlags = $recipeData['dietary_flags'];

            unset($recipeData['ingredients'], $recipeData['equipment'], $recipeData['dietary_flags']);

            $recipeData['created_at'] = $now;
            $recipeData['updated_at'] = $now;

            // Insert recipe and get ID
            $recipeId = DB::table('recipes')->insertGetId($recipeData);

            // Insert recipe_ingredients
            foreach ($recipeIngredients as $ing) {
                if (isset($ingredients[$ing['name']])) {
                    DB::table('recipe_ingredients')->insert([
                        'recipe_id' => $recipeId,
                        'ingredient_id' => $ingredients[$ing['name']],
                        'quantity' => $ing['quantity'],
                        'unit' => $ing['unit'],
                        'estimated_cost' => $ing['estimated_cost'],
                        'created_at' => $now,
                        'updated_at' => $now,
                    ]);
                }
            }

            // Insert recipe_equipment
            foreach ($recipeEquipment as $equip) {
                if (isset($equipment[$equip])) {
                    DB::table('recipe_equipment')->insert([
                        'recipe_id' => $recipeId,
                        'equipment_id' => $equipment[$equip],
                        'created_at' => $now,
                        'updated_at' => $now,
                    ]);
                }
            }

            // Insert recipe_dietary_flags
            foreach ($recipeDietaryFlags as $flag) {
                if (isset($dietaryRestrictions[$flag])) {
                    DB::table('recipe_dietary_flags')->insert([
                        'recipe_id' => $recipeId,
                        'dietary_restriction_id' => $dietaryRestrictions[$flag],
                        'created_at' => $now,
                        'updated_at' => $now,
                    ]);
                }
            }
        }
    }
}
